import sys; sys.setdlopenflags(0x00100|sys.getdlopenflags())
import sys; sys.setdlopenflags(0x00100|sys.getdlopenflags())
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_model', [dirname(__file__)])
        except ImportError:
            import _model
            return _model
        if fp is not None:
            try:
                _mod = imp.load_module('_model', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _model = swig_import_helper()
    del swig_import_helper
else:
    import _model
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _setstate( self, state ):
    if not hasattr( self, 'this' ) : self.__init__()
    self.__C_setstate__(state)
def import_aivlib(tgt) :
    name = tgt.split('-')[0]
    try : exec('import aivlib.'+name)
    except ImportError, e : import os; os.system('make-aivlib %r'%tgt); exec('import aivlib.'+name)
    return eval('aivlib.'+name)
def _swig_setattr(self,class_type,name,value):
    if name in class_type.__swig_setmethods__ : value = getattr( self, name ).__class__(value)
    return _swig_setattr_nondynamic(self,class_type,name,value,0)
__makefile__='model.mk'

class aiv_convert_for_compare_float(_object):
    """Proxy of C++ std::aiv_convert_for_compare_float class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, aiv_convert_for_compare_float, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, aiv_convert_for_compare_float, name)
    __repr__ = _swig_repr
    __swig_setmethods__["flt"] = _model.aiv_convert_for_compare_float_flt_set
    __swig_getmethods__["flt"] = _model.aiv_convert_for_compare_float_flt_get
    if _newclass:flt = _swig_property(_model.aiv_convert_for_compare_float_flt_get, _model.aiv_convert_for_compare_float_flt_set)
    __swig_setmethods__["fix"] = _model.aiv_convert_for_compare_float_fix_set
    __swig_getmethods__["fix"] = _model.aiv_convert_for_compare_float_fix_get
    if _newclass:fix = _swig_property(_model.aiv_convert_for_compare_float_fix_get, _model.aiv_convert_for_compare_float_fix_set)
    def __init__(self): 
        """__init__(std::aiv_convert_for_compare_float self) -> aiv_convert_for_compare_float"""
        this = _model.new_aiv_convert_for_compare_float()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_aiv_convert_for_compare_float
    __del__ = lambda self : None;
aiv_convert_for_compare_float_swigregister = _model.aiv_convert_for_compare_float_swigregister
aiv_convert_for_compare_float_swigregister(aiv_convert_for_compare_float)

class _base_mem(_object):
    """Proxy of C++ aiv::_base_mem class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _base_mem, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _base_mem, name)
    __repr__ = _swig_repr
    __swig_getmethods__["D"] = _model._base_mem_D_get
    if _newclass:D = _swig_property(_model._base_mem_D_get)
    __swig_getmethods__["szT"] = _model._base_mem_szT_get
    if _newclass:szT = _swig_property(_model._base_mem_szT_get)
    __swig_setmethods__["N"] = _model._base_mem_N_set
    __swig_getmethods__["N"] = _model._base_mem_N_get
    if _newclass:N = _swig_property(_model._base_mem_N_get, _model._base_mem_N_set)
    __swig_setmethods__["owners"] = _model._base_mem_owners_set
    __swig_getmethods__["owners"] = _model._base_mem_owners_get
    if _newclass:owners = _swig_property(_model._base_mem_owners_get, _model._base_mem_owners_set)
    def __init__(self, *args): 
        """__init__(aiv::_base_mem self, int AszT, int AD, int * AN) -> _base_mem"""
        this = _model.new__base_mem(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete__base_mem
    __del__ = lambda self : None;
    def len(self):
        """len(_base_mem self) -> size_t"""
        return _model._base_mem_len(self)

_base_mem_swigregister = _model._base_mem_swigregister
_base_mem_swigregister(_base_mem)

class arr_head(_object):
    """Proxy of C++ aiv::arr_head class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, arr_head, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, arr_head, name)
    __repr__ = _swig_repr
    __swig_getmethods__["D"] = _model.arr_head_D_get
    if _newclass:D = _swig_property(_model.arr_head_D_get)
    __swig_getmethods__["szT"] = _model.arr_head_szT_get
    if _newclass:szT = _swig_property(_model.arr_head_szT_get)
    __swig_getmethods__["N"] = _model.arr_head_N_get
    if _newclass:N = _swig_property(_model.arr_head_N_get)
    def load(self, *args):
        """load(arr_head self, aiv::Istream & S)"""
        return _model.arr_head_load(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::arr_head self) -> arr_head
        __init__(aiv::arr_head self, aiv::Istream & S) -> arr_head
        __init__(aiv::arr_head self, arr_head H) -> arr_head
        """
        this = _model.new_arr_head(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_arr_head
    __del__ = lambda self : None;
arr_head_swigregister = _model.arr_head_swigregister
arr_head_swigregister(arr_head)

class lrc_head(_object):
    """Proxy of C++ aiv::lrc_head class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lrc_head, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lrc_head, name)
    __repr__ = _swig_repr
    __swig_getmethods__["D"] = _model.lrc_head_D_get
    if _newclass:D = _swig_property(_model.lrc_head_D_get)
    __swig_getmethods__["D2"] = _model.lrc_head_D2_get
    if _newclass:D2 = _swig_property(_model.lrc_head_D2_get)
    __swig_getmethods__["szT"] = _model.lrc_head_szT_get
    if _newclass:szT = _swig_property(_model.lrc_head_szT_get)
    __swig_getmethods__["R"] = _model.lrc_head_R_get
    if _newclass:R = _swig_property(_model.lrc_head_R_get)
    __swig_getmethods__["N"] = _model.lrc_head_N_get
    if _newclass:N = _swig_property(_model.lrc_head_N_get)
    __swig_destroy__ = _model.delete_lrc_head
    __del__ = lambda self : None;
    def load(self, *args):
        """load(lrc_head self, aiv::Istream & S)"""
        return _model.lrc_head_load(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::lrc_head self) -> lrc_head
        __init__(aiv::lrc_head self, aiv::Istream & S) -> lrc_head
        __init__(aiv::lrc_head self, lrc_head H) -> lrc_head
        """
        this = _model.new_lrc_head(*args)
        try: self.this.append(this)
        except: self.this = this
lrc_head_swigregister = _model.lrc_head_swigregister
lrc_head_swigregister(lrc_head)

class base_sphere(_object):
    """Proxy of C++ aiv::base_sphere class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, base_sphere, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, base_sphere, name)
    __repr__ = _swig_repr
    __swig_getmethods__["R"] = _model.base_sphere_R_get
    if _newclass:R = _swig_property(_model.base_sphere_R_get)
    __swig_getmethods__["N"] = _model.base_sphere_N_get
    if _newclass:N = _swig_property(_model.base_sphere_N_get)
    def get_ref_count(self):
        """get_ref_count(base_sphere self) -> int"""
        return _model.base_sphere_get_ref_count(self)

    def __init__(self, *args): 
        """
        __init__(aiv::base_sphere self, int AR=-1) -> base_sphere
        __init__(aiv::base_sphere self) -> base_sphere
        __init__(aiv::base_sphere self, base_sphere S) -> base_sphere
        """
        this = _model.new_base_sphere(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_base_sphere
    __del__ = lambda self : None;
    def init(self, *args):
        """init(base_sphere self, int AR)"""
        return _model.base_sphere_init(self, *args)

    def get_cell_id(self, *args):
        """get_cell_id(base_sphere self, vctr3 r) -> int"""
        return _model.base_sphere_get_cell_id(self, *args)

    def get_cell_vertex(self, *args):
        """get_cell_vertex(base_sphere self, int cid) -> indx3"""
        return _model.base_sphere_get_cell_vertex(self, *args)

    def get_vertex(self, *args):
        """get_vertex(base_sphere self, int vid) -> vctr3"""
        return _model.base_sphere_get_vertex(self, *args)

    def get_cell_neighbours(self, *args):
        """get_cell_neighbours(base_sphere self, int cid) -> indx3"""
        return _model.base_sphere_get_cell_neighbours(self, *args)

    def get_vertex_cells(self, *args):
        """get_vertex_cells(base_sphere self, int vid) -> aiv::indx< 6 > const &"""
        return _model.base_sphere_get_vertex_cells(self, *args)

    def get_cell_area(self, *args):
        """get_cell_area(base_sphere self, int cid) -> double"""
        return _model.base_sphere_get_cell_area(self, *args)

    def get_coord(self, *args):
        """get_coord(base_sphere self, vctr3 x, long i, int AR)"""
        return _model.base_sphere_get_coord(self, *args)

    def get_nb(self, *args):
        """get_nb(base_sphere self, long * nb, long i, int AR)"""
        return _model.base_sphere_get_nb(self, *args)

    def get_cell_center(self, *args):
        """
        get_cell_center(base_sphere self, int cid) -> vctr3
        get_cell_center(base_sphere self, long cid, int AR) -> vctr3
        """
        return _model.base_sphere_get_cell_center(self, *args)

base_sphere_swigregister = _model.base_sphere_swigregister
base_sphere_swigregister(base_sphere)
cvar = _model.cvar
MAX_RANK = cvar.MAX_RANK


def barecentr(*args):
  """barecentr(vctr3 x, vctr3 r) -> vctr3"""
  return _model.barecentr(*args)
class Atom(_object):
    """Proxy of C++ Atom class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Atom, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Atom, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m1"] = _model.Atom_m1_set
    __swig_getmethods__["m1"] = _model.Atom_m1_get
    if _newclass:m1 = _swig_property(_model.Atom_m1_get, _model.Atom_m1_set)
    __swig_setmethods__["m0"] = _model.Atom_m0_set
    __swig_getmethods__["m0"] = _model.Atom_m0_get
    if _newclass:m0 = _swig_property(_model.Atom_m0_get, _model.Atom_m0_set)
    def stage1(self, *args):
        """stage1(Atom self, Model model, aiv::vctr< 3 > const & Hexch, aiv::vctr< 3 > const & Haniso)"""
        return _model.Atom_stage1(self, *args)

    def stage2(self, *args):
        """stage2(Atom self, Model model)"""
        return _model.Atom_stage2(self, *args)

    def __init__(self): 
        """__init__(Atom self) -> Atom"""
        this = _model.new_Atom()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Atom
    __del__ = lambda self : None;
Atom_swigregister = _model.Atom_swigregister
Atom_swigregister(Atom)

class Aniso(_object):
    """Proxy of C++ Aniso class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Aniso, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Aniso, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n"] = _model.Aniso_n_set
    __swig_getmethods__["n"] = _model.Aniso_n_get
    if _newclass:n = _swig_property(_model.Aniso_n_get, _model.Aniso_n_set)
    __swig_setmethods__["K"] = _model.Aniso_K_set
    __swig_getmethods__["K"] = _model.Aniso_K_get
    if _newclass:K = _swig_property(_model.Aniso_K_get, _model.Aniso_K_set)
    def __init__(self): 
        """__init__(Aniso self) -> Aniso"""
        this = _model.new_Aniso()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Aniso
    __del__ = lambda self : None;
Aniso_swigregister = _model.Aniso_swigregister
Aniso_swigregister(Aniso)

class Model(_object):
    """Proxy of C++ Model class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Model, name)
    __repr__ = _swig_repr
    __swig_setmethods__["h"] = _model.Model_h_set
    __swig_getmethods__["h"] = _model.Model_h_get
    if _newclass:h = _swig_property(_model.Model_h_get, _model.Model_h_set)
    __swig_setmethods__["Hext"] = _model.Model_Hext_set
    __swig_getmethods__["Hext"] = _model.Model_Hext_get
    if _newclass:Hext = _swig_property(_model.Model_Hext_get, _model.Model_Hext_set)
    __swig_setmethods__["gamma"] = _model.Model_gamma_set
    __swig_getmethods__["gamma"] = _model.Model_gamma_get
    if _newclass:gamma = _swig_property(_model.Model_gamma_get, _model.Model_gamma_set)
    __swig_setmethods__["alpha"] = _model.Model_alpha_set
    __swig_getmethods__["alpha"] = _model.Model_alpha_get
    if _newclass:alpha = _swig_property(_model.Model_alpha_get, _model.Model_alpha_set)
    __swig_setmethods__["time"] = _model.Model_time_set
    __swig_getmethods__["time"] = _model.Model_time_get
    if _newclass:time = _swig_property(_model.Model_time_get, _model.Model_time_set)
    __swig_setmethods__["Natoms"] = _model.Model_Natoms_set
    __swig_getmethods__["Natoms"] = _model.Model_Natoms_get
    if _newclass:Natoms = _swig_property(_model.Model_Natoms_get, _model.Model_Natoms_set)
    def get_J(self, *args):
        """get_J(Model self, int l1, int l2) -> double"""
        return _model.Model_get_J(self, *args)

    def set_J(self, *args):
        """set_J(Model self, int l1, int l2, double J)"""
        return _model.Model_set_J(self, *args)

    def add_K1(self, *args):
        """add_K1(Model self, Aniso aniso, int lattice)"""
        return _model.Model_add_K1(self, *args)

    def add_K3(self, *args):
        """add_K3(Model self, Aniso aniso, int lattice)"""
        return _model.Model_add_K3(self, *args)

    def step(self):
        """step(Model self)"""
        return _model.Model_step(self)

    __swig_setmethods__["trans"] = _model.Model_trans_set
    __swig_getmethods__["trans"] = _model.Model_trans_get
    if _newclass:trans = _swig_property(_model.Model_trans_get, _model.Model_trans_set)
    def init(self, *args):
        """init(Model self, BaseFigure figure, GlobalTrans trans)"""
        return _model.Model_init(self, *args)

    def dump_head(self, *args):
        """dump_head(Model self, aiv::Ostream & S)"""
        return _model.Model_dump_head(self, *args)

    def dump_data(self, *args):
        """dump_data(Model self, aiv::Ostream & S)"""
        return _model.Model_dump_data(self, *args)

    def init_diag(self, *args):
        """init_diag(Model self, aiv::Ostream & S)"""
        return _model.Model_init_diag(self, *args)

    def dump_diag(self, *args):
        """dump_diag(Model self, aiv::Ostream & S)"""
        return _model.Model_dump_diag(self, *args)

    def simplestart(self, *args):
        """simplestart(Model self, aiv::vctr< 3 > const & mstart)"""
        return _model.Model_simplestart(self, *args)

    def total_cells(self):
        """total_cells(Model self) -> int"""
        return _model.Model_total_cells(self)

    def total_cells_x(self):
        """total_cells_x(Model self) -> int"""
        return _model.Model_total_cells_x(self)

    def total_cells_y(self):
        """total_cells_y(Model self) -> int"""
        return _model.Model_total_cells_y(self)

    def total_cells_z(self):
        """total_cells_z(Model self) -> int"""
        return _model.Model_total_cells_z(self)

    def used_cells(self):
        """used_cells(Model self) -> int"""
        return _model.Model_used_cells(self)

    def border_space(self):
        """border_space(Model self)"""
        return _model.Model_border_space(self)

    def text_dump(self):
        """text_dump(Model self)"""
        return _model.Model_text_dump(self)

    def __init__(self): 
        """__init__(Model self) -> Model"""
        this = _model.new_Model()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Model
    __del__ = lambda self : None;
Model_swigregister = _model.Model_swigregister
Model_swigregister(Model)

class Cell(_object):
    """Proxy of C++ Cell class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cell, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cell, name)
    __repr__ = _swig_repr
    __swig_setmethods__["atoms"] = _model.Cell_atoms_set
    __swig_getmethods__["atoms"] = _model.Cell_atoms_get
    if _newclass:atoms = _swig_property(_model.Cell_atoms_get, _model.Cell_atoms_set)
    __swig_setmethods__["usage"] = _model.Cell_usage_set
    __swig_getmethods__["usage"] = _model.Cell_usage_get
    if _newclass:usage = _swig_property(_model.Cell_usage_get, _model.Cell_usage_set)
    def __init__(self): 
        """__init__(Cell self) -> Cell"""
        this = _model.new_Cell()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Cell
    __del__ = lambda self : None;
Cell_swigregister = _model.Cell_swigregister
Cell_swigregister(Cell)

class GlobalTrans(_object):
    """Proxy of C++ GlobalTrans class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GlobalTrans, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GlobalTrans, name)
    __repr__ = _swig_repr
    __swig_setmethods__["I1"] = _model.GlobalTrans_I1_set
    __swig_getmethods__["I1"] = _model.GlobalTrans_I1_get
    if _newclass:I1 = _swig_property(_model.GlobalTrans_I1_get, _model.GlobalTrans_I1_set)
    __swig_setmethods__["I2"] = _model.GlobalTrans_I2_set
    __swig_getmethods__["I2"] = _model.GlobalTrans_I2_get
    if _newclass:I2 = _swig_property(_model.GlobalTrans_I2_get, _model.GlobalTrans_I2_set)
    __swig_setmethods__["I3"] = _model.GlobalTrans_I3_set
    __swig_getmethods__["I3"] = _model.GlobalTrans_I3_get
    if _newclass:I3 = _swig_property(_model.GlobalTrans_I3_get, _model.GlobalTrans_I3_set)
    def __init__(self, *args): 
        """
        __init__(GlobalTrans self) -> GlobalTrans
        __init__(GlobalTrans self, aiv::vctr< 3 > i1, aiv::vctr< 3 > i2, aiv::vctr< 3 > i3) -> GlobalTrans
        """
        this = _model.new_GlobalTrans(*args)
        try: self.this.append(this)
        except: self.this = this
    def trans_vec(self, *args):
        """trans_vec(GlobalTrans self, vctr3 r) -> aiv::vctr< 3 >"""
        return _model.GlobalTrans_trans_vec(self, *args)

    def trans_vec_back(self, *args):
        """trans_vec_back(GlobalTrans self, vctr3 r) -> aiv::vctr< 3 >"""
        return _model.GlobalTrans_trans_vec_back(self, *args)

    __swig_destroy__ = _model.delete_GlobalTrans
    __del__ = lambda self : None;
GlobalTrans_swigregister = _model.GlobalTrans_swigregister
GlobalTrans_swigregister(GlobalTrans)

class BaseFigure(_object):
    """Proxy of C++ BaseFigure class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BaseFigure, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BaseFigure, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def get_minxyz(self):
        """get_minxyz(BaseFigure self) -> aiv::vctr< 3 >"""
        return _model.BaseFigure_get_minxyz(self)

    def get_maxxyz(self):
        """get_maxxyz(BaseFigure self) -> aiv::vctr< 3 >"""
        return _model.BaseFigure_get_maxxyz(self)

    def check(self, *args):
        """check(BaseFigure self, vctr3 r) -> bool"""
        return _model.BaseFigure_check(self, *args)

    __swig_destroy__ = _model.delete_BaseFigure
    __del__ = lambda self : None;
BaseFigure_swigregister = _model.BaseFigure_swigregister
BaseFigure_swigregister(BaseFigure)

class Cylinder(BaseFigure):
    """Proxy of C++ Cylinder class"""
    __swig_setmethods__ = {}
    for _s in [BaseFigure]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cylinder, name, value)
    __swig_getmethods__ = {}
    for _s in [BaseFigure]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Cylinder, name)
    __repr__ = _swig_repr
    __swig_setmethods__["center"] = _model.Cylinder_center_set
    __swig_getmethods__["center"] = _model.Cylinder_center_get
    if _newclass:center = _swig_property(_model.Cylinder_center_get, _model.Cylinder_center_set)
    __swig_setmethods__["R"] = _model.Cylinder_R_set
    __swig_getmethods__["R"] = _model.Cylinder_R_get
    if _newclass:R = _swig_property(_model.Cylinder_R_get, _model.Cylinder_R_set)
    __swig_setmethods__["H"] = _model.Cylinder_H_set
    __swig_getmethods__["H"] = _model.Cylinder_H_get
    if _newclass:H = _swig_property(_model.Cylinder_H_get, _model.Cylinder_H_set)
    def get_minxyz(self):
        """get_minxyz(Cylinder self) -> aiv::vctr< 3 >"""
        return _model.Cylinder_get_minxyz(self)

    def get_maxxyz(self):
        """get_maxxyz(Cylinder self) -> aiv::vctr< 3 >"""
        return _model.Cylinder_get_maxxyz(self)

    def check(self, *args):
        """check(Cylinder self, vctr3 r) -> bool"""
        return _model.Cylinder_check(self, *args)

    def __init__(self, *args): 
        """
        __init__(Cylinder self) -> Cylinder
        __init__(Cylinder self, aiv::vctr< 3 > c, double r, double h) -> Cylinder
        """
        this = _model.new_Cylinder(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Cylinder
    __del__ = lambda self : None;
Cylinder_swigregister = _model.Cylinder_swigregister
Cylinder_swigregister(Cylinder)

class Cube(BaseFigure):
    """Proxy of C++ Cube class"""
    __swig_setmethods__ = {}
    for _s in [BaseFigure]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cube, name, value)
    __swig_getmethods__ = {}
    for _s in [BaseFigure]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Cube, name)
    __repr__ = _swig_repr
    __swig_setmethods__["center"] = _model.Cube_center_set
    __swig_getmethods__["center"] = _model.Cube_center_get
    if _newclass:center = _swig_property(_model.Cube_center_get, _model.Cube_center_set)
    __swig_setmethods__["A"] = _model.Cube_A_set
    __swig_getmethods__["A"] = _model.Cube_A_get
    if _newclass:A = _swig_property(_model.Cube_A_get, _model.Cube_A_set)
    def get_minxyz(self):
        """get_minxyz(Cube self) -> aiv::vctr< 3 >"""
        return _model.Cube_get_minxyz(self)

    def get_maxxyz(self):
        """get_maxxyz(Cube self) -> aiv::vctr< 3 >"""
        return _model.Cube_get_maxxyz(self)

    def check(self, *args):
        """check(Cube self, vctr3 r) -> bool"""
        return _model.Cube_check(self, *args)

    def __init__(self, *args): 
        """
        __init__(Cube self) -> Cube
        __init__(Cube self, aiv::vctr< 3 > c, double a) -> Cube
        """
        this = _model.new_Cube(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Cube
    __del__ = lambda self : None;
Cube_swigregister = _model.Cube_swigregister
Cube_swigregister(Cube)

class Box(BaseFigure):
    """Proxy of C++ Box class"""
    __swig_setmethods__ = {}
    for _s in [BaseFigure]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Box, name, value)
    __swig_getmethods__ = {}
    for _s in [BaseFigure]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Box, name)
    __repr__ = _swig_repr
    __swig_setmethods__["center"] = _model.Box_center_set
    __swig_getmethods__["center"] = _model.Box_center_get
    if _newclass:center = _swig_property(_model.Box_center_get, _model.Box_center_set)
    __swig_setmethods__["A"] = _model.Box_A_set
    __swig_getmethods__["A"] = _model.Box_A_get
    if _newclass:A = _swig_property(_model.Box_A_get, _model.Box_A_set)
    __swig_setmethods__["B"] = _model.Box_B_set
    __swig_getmethods__["B"] = _model.Box_B_get
    if _newclass:B = _swig_property(_model.Box_B_get, _model.Box_B_set)
    __swig_setmethods__["H"] = _model.Box_H_set
    __swig_getmethods__["H"] = _model.Box_H_get
    if _newclass:H = _swig_property(_model.Box_H_get, _model.Box_H_set)
    def get_minxyz(self):
        """get_minxyz(Box self) -> aiv::vctr< 3 >"""
        return _model.Box_get_minxyz(self)

    def get_maxxyz(self):
        """get_maxxyz(Box self) -> aiv::vctr< 3 >"""
        return _model.Box_get_maxxyz(self)

    def check(self, *args):
        """check(Box self, vctr3 r) -> bool"""
        return _model.Box_check(self, *args)

    def __init__(self, *args): 
        """
        __init__(Box self) -> Box
        __init__(Box self, aiv::vctr< 3 > c, double a, double b, double h) -> Box
        """
        this = _model.new_Box(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_Box
    __del__ = lambda self : None;
Box_swigregister = _model.Box_swigregister
Box_swigregister(Box)

class SetFigures(BaseFigure):
    """Proxy of C++ SetFigures class"""
    __swig_setmethods__ = {}
    for _s in [BaseFigure]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SetFigures, name, value)
    __swig_getmethods__ = {}
    for _s in [BaseFigure]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, SetFigures, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Figures"] = _model.SetFigures_Figures_set
    __swig_getmethods__["Figures"] = _model.SetFigures_Figures_get
    if _newclass:Figures = _swig_property(_model.SetFigures_Figures_get, _model.SetFigures_Figures_set)
    def add(self, *args):
        """add(SetFigures self, BaseFigure figure)"""
        return _model.SetFigures_add(self, *args)

    def get_minxyz(self):
        """get_minxyz(SetFigures self) -> aiv::vctr< 3 >"""
        return _model.SetFigures_get_minxyz(self)

    def get_maxxyz(self):
        """get_maxxyz(SetFigures self) -> aiv::vctr< 3 >"""
        return _model.SetFigures_get_maxxyz(self)

    def check(self, *args):
        """check(SetFigures self, vctr3 r) -> bool"""
        return _model.SetFigures_check(self, *args)

    def __init__(self): 
        """__init__(SetFigures self) -> SetFigures"""
        this = _model.new_SetFigures()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _model.delete_SetFigures
    __del__ = lambda self : None;
SetFigures_swigregister = _model.SetFigures_swigregister
SetFigures_swigregister(SetFigures)

class indx1(_object):
    """Proxy of C++ aiv::indx<(1)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, indx1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, indx1, name)
    def volume(self):
        """volume(indx1 self) -> long"""
        return _model.indx1_volume(self)

    def __lt__(self, *args):
        """
        __lt__(indx1 self, indx1 r) -> bool
        __lt__(indx1 self, PyObject * t) -> bool
        __lt__(indx1 self, long i) -> bool
        """
        return _model.indx1___lt__(self, *args)

    def __le__(self, *args):
        """
        __le__(indx1 self, indx1 r) -> bool
        __le__(indx1 self, PyObject * t) -> bool
        __le__(indx1 self, long i) -> bool
        """
        return _model.indx1___le__(self, *args)

    def __gt__(self, *args):
        """
        __gt__(indx1 self, indx1 r) -> bool
        __gt__(indx1 self, PyObject * t) -> bool
        __gt__(indx1 self, long i) -> bool
        """
        return _model.indx1___gt__(self, *args)

    def __ge__(self, *args):
        """
        __ge__(indx1 self, indx1 r) -> bool
        __ge__(indx1 self, PyObject * t) -> bool
        __ge__(indx1 self, long i) -> bool
        """
        return _model.indx1___ge__(self, *args)

    def __eq__(self, *args):
        """
        __eq__(indx1 self, indx1 r) -> bool
        __eq__(indx1 self, PyObject * t) -> bool
        __eq__(indx1 self, long i) -> bool
        """
        return _model.indx1___eq__(self, *args)

    def __ne__(self, *args):
        """
        __ne__(indx1 self, indx1 r) -> bool
        __ne__(indx1 self, PyObject * t) -> bool
        __ne__(indx1 self, long i) -> bool
        """
        return _model.indx1___ne__(self, *args)

    def __add__(self, *args):
        """
        __add__(indx1 self, indx1 r) -> indx1
        __add__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(indx1 self, indx1 r) -> indx1
        __sub__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___sub__(self, *args)

    def __xor__(self, *args):
        """
        __xor__(indx1 self, indx1 r) -> indx1
        __xor__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___xor__(self, *args)

    def __mul__(self, *args):
        """
        __mul__(indx1 self, indx1 r) -> long
        __mul__(indx1 self, int j) -> indx1
        """
        return _model.indx1___mul__(self, *args)

    def __imul__(self, *args):
        """__imul__(indx1 self, int j) -> indx1"""
        return _model.indx1___imul__(self, *args)

    def __neg__(self):
        """__neg__(indx1 self) -> indx1"""
        return _model.indx1___neg__(self)

    def __ixor__(self, *args):
        """
        __ixor__(indx1 self, indx1 r) -> indx1
        __ixor__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___ixor__(self, *args)

    def __iadd__(self, *args):
        """
        __iadd__(indx1 self, indx1 r) -> indx1
        __iadd__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___iadd__(self, *args)

    def __isub__(self, *args):
        """
        __isub__(indx1 self, indx1 r) -> indx1
        __isub__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___isub__(self, *args)

    def __lshift__(self, *args):
        """
        __lshift__(indx1 self, indx1 b) -> indx1
        __lshift__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___lshift__(self, *args)

    def __rshift__(self, *args):
        """
        __rshift__(indx1 self, indx1 b) -> indx1
        __rshift__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___rshift__(self, *args)

    def __ilshift__(self, *args):
        """
        __ilshift__(indx1 self, indx1 b) -> indx1
        __ilshift__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___ilshift__(self, *args)

    def __irshift__(self, *args):
        """
        __irshift__(indx1 self, indx1 b) -> indx1
        __irshift__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___irshift__(self, *args)

    def __mod__(self, *args):
        """
        __mod__(indx1 self, indx1 b) -> indx1
        __mod__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___mod__(self, *args)

    def __imod__(self, *args):
        """
        __imod__(indx1 self, indx1 b) -> indx1
        __imod__(indx1 self, PyObject * t) -> indx1
        """
        return _model.indx1___imod__(self, *args)

    def __rmod__(self, *args):
        """__rmod__(indx1 self, long x) -> indx1"""
        return _model.indx1___rmod__(self, *args)

    def __div__(self, *args):
        """
        __div__(indx1 self, indx1 b) -> indx1
        __div__(indx1 self, PyObject * t) -> indx1
        __div__(indx1 self, int x) -> indx1
        """
        return _model.indx1___div__(self, *args)

    def __idiv__(self, *args):
        """
        __idiv__(indx1 self, indx1 b) -> indx1
        __idiv__(indx1 self, PyObject * t) -> indx1
        __idiv__(indx1 self, int x) -> indx1
        """
        return _model.indx1___idiv__(self, *args)

    def circ(self, *args):
        """circ(indx1 self, int l) -> indx1"""
        return _model.indx1_circ(self, *args)

    def c_str(self, separator=" ", format="%i"):
        """
        c_str(indx1 self, char const * separator=" ", char const * format="%i") -> char const
        c_str(indx1 self, char const * separator=" ") -> char const
        c_str(indx1 self) -> char const *
        """
        return _model.indx1_c_str(self, separator, format)

    def __contains__(self, *args):
        """__contains__(indx1 self, indx1 I) -> bool"""
        return _model.indx1___contains__(self, *args)

    def __rmul__(self, *args):
        """__rmul__(indx1 self, int x) -> indx1"""
        return _model.indx1___rmul__(self, *args)

    def __len__(self):
        """__len__(indx1 self) -> int const"""
        return _model.indx1___len__(self)

    def __int__(self):
        """__int__(indx1 self) -> long"""
        return _model.indx1___int__(self)

    def __getitem__(self, *args):
        """__getitem__(indx1 self, int i) -> int"""
        return _model.indx1___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(indx1 self, int i, int x)"""
        return _model.indx1___setitem__(self, *args)

    def __getslice__(self, *args):
        """__getslice__(indx1 self, long a, long b) -> PyObject *"""
        return _model.indx1___getslice__(self, *args)

    def __setslice__(self, *args):
        """__setslice__(indx1 self, long a, long b, PyObject * t)"""
        return _model.indx1___setslice__(self, *args)

    def __str__(self):
        """__str__(indx1 self) -> PyObject *"""
        return _model.indx1___str__(self)

    def __repr__(self):
        """__repr__(indx1 self) -> PyObject *"""
        return _model.indx1___repr__(self)

    def __getstate__(self):
        """__getstate__(indx1 self) -> PyObject *"""
        return _model.indx1___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(indx1 self, PyObject * t)"""
        return _model.indx1___C_setstate__(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::indx<(1)> self, int val=0) -> indx1
        __init__(aiv::indx<(1)> self) -> indx1
        __init__(aiv::indx<(1)> self, int const * Ap) -> indx1
        __init__(aiv::indx<(1)> self, PyObject * t) -> indx1
        """
        this = _model.new_indx1(*args)
        try: self.this.append(this)
        except: self.this = this
    def __hash__(self):
        """__hash__(indx1 self) -> long"""
        return _model.indx1___hash__(self)

    def py_debug_info(self, *args):
        """py_debug_info(indx1 self, aiv::debug_info & S)"""
        return _model.indx1_py_debug_info(self, *args)

    def less(self, *args):
        """
        less(indx1 self, indx1 N) -> bool
        less(indx1 self, indx1 N, int const seq) -> bool
        """
        return _model.indx1_less(self, *args)

    def next(self, *args):
        """
        next(indx1 self, indx1 finish) -> bool
        next(indx1 self, indx1 start, indx1 finish) -> bool
        next(indx1 self, indx1 start, indx1 finish, int const seq, int const direct=0) -> bool
        next(indx1 self, indx1 start, indx1 finish, int const seq) -> bool
        next(indx1 self, indx1 finish, int const seq, int const direct=0) -> bool
        next(indx1 self, indx1 finish, int const seq) -> bool
        """
        return _model.indx1_next(self, *args)

    def z_next(self, *args):
        """
        z_next(indx1 self, int const rank) -> bool
        z_next(indx1 self, int const rank, int const seq) -> bool
        """
        return _model.indx1_z_next(self, *args)

    __swig_destroy__ = _model.delete_indx1
    __del__ = lambda self : None;
indx1_swigregister = _model.indx1_swigregister
indx1_swigregister(indx1)

def Indx( *L ) : v = getattr( import_aivlib( 'indx%i'%len(L) ), 'indx%i'%len(L) )(); v[:] = tuple(L); return v
indx1.__rcmp__=lambda a,b : -b.__cmp__(a) 
def _indx1__xor__( a,b ) :  
  try : return Indx(*map( int.__mul__, tuple(a),tuple(b) ) )  
  except : return  Indx(*(tuple(a)[:b]+tuple(a)[b+1:]))
indx1.__xor__ = _indx1__xor__ 
indx1.__or__ =lambda a,b : Indx(*(tuple(a)+tuple(((b,),b)[b.__class__.__name__.startswith('indx')])))  
indx1.__ror__=lambda a,b : Indx(*(tuple(((b,),b)[b.__class__.__name__.startswith('indx')])+tuple(a)))  
indx1.__setstate__ = _setstate 

class vctr1(_object):
    """Proxy of C++ aiv::vctr<(1,double)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vctr1, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vctr1, name)
    def __lt__(self, *args):
        """
        __lt__(vctr1 self, vctr1 r) -> bool
        __lt__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___lt__(self, *args)

    def __le__(self, *args):
        """
        __le__(vctr1 self, vctr1 r) -> bool
        __le__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___le__(self, *args)

    def __gt__(self, *args):
        """
        __gt__(vctr1 self, vctr1 r) -> bool
        __gt__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___gt__(self, *args)

    def __ge__(self, *args):
        """
        __ge__(vctr1 self, vctr1 r) -> bool
        __ge__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___ge__(self, *args)

    def __eq__(self, *args):
        """
        __eq__(vctr1 self, vctr1 r) -> bool
        __eq__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___eq__(self, *args)

    def __ne__(self, *args):
        """
        __ne__(vctr1 self, vctr1 r) -> bool
        __ne__(vctr1 self, PyObject * t) -> bool
        """
        return _model.vctr1___ne__(self, *args)

    def __and__(self, *args):
        """
        __and__(vctr1 self, vctr1 r) -> double
        __and__(vctr1 self, PyObject * t) -> double
        """
        return _model.vctr1___and__(self, *args)

    def __add__(self, *args):
        """
        __add__(vctr1 self, vctr1 r) -> vctr1
        __add__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(vctr1 self, vctr1 r) -> vctr1
        __sub__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___sub__(self, *args)

    def __iadd__(self, *args):
        """
        __iadd__(vctr1 self, vctr1 r) -> vctr1
        __iadd__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___iadd__(self, *args)

    def __isub__(self, *args):
        """
        __isub__(vctr1 self, vctr1 r) -> vctr1
        __isub__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___isub__(self, *args)

    def __lshift__(self, *args):
        """
        __lshift__(vctr1 self, vctr1 r) -> vctr1
        __lshift__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___lshift__(self, *args)

    def __rshift__(self, *args):
        """
        __rshift__(vctr1 self, vctr1 r) -> vctr1
        __rshift__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___rshift__(self, *args)

    def __ilshift__(self, *args):
        """
        __ilshift__(vctr1 self, vctr1 r) -> vctr1
        __ilshift__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___ilshift__(self, *args)

    def __irshift__(self, *args):
        """
        __irshift__(vctr1 self, vctr1 r) -> vctr1
        __irshift__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___irshift__(self, *args)

    def __xor__(self, *args):
        """
        __xor__(vctr1 self, vctr1 r) -> vctr1
        __xor__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___xor__(self, *args)

    def __ixor__(self, *args):
        """
        __ixor__(vctr1 self, vctr1 r) -> vctr1
        __ixor__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___ixor__(self, *args)

    def __mul__(self, *args):
        """
        __mul__(vctr1 self, vctr1 r) -> double
        __mul__(vctr1 self, indx1 I) -> vctr1
        __mul__(vctr1 self, PyObject * t) -> vctr1
        __mul__(vctr1 self, double x) -> vctr1
        """
        return _model.vctr1___mul__(self, *args)

    def __imul__(self, *args):
        """
        __imul__(vctr1 self, indx1 I) -> vctr1
        __imul__(vctr1 self, PyObject * t) -> vctr1
        __imul__(vctr1 self, double x) -> vctr1
        """
        return _model.vctr1___imul__(self, *args)

    def __div__(self, *args):
        """
        __div__(vctr1 self, vctr1 r) -> indx1
        __div__(vctr1 self, indx1 I) -> vctr1
        __div__(vctr1 self, PyObject * t) -> vctr1
        __div__(vctr1 self, double x) -> vctr1
        """
        return _model.vctr1___div__(self, *args)

    def __idiv__(self, *args):
        """
        __idiv__(vctr1 self, indx1 I) -> vctr1
        __idiv__(vctr1 self, PyObject * t) -> vctr1
        __idiv__(vctr1 self, double x) -> vctr1
        """
        return _model.vctr1___idiv__(self, *args)

    def __neg__(self):
        """__neg__(vctr1 self) -> vctr1"""
        return _model.vctr1___neg__(self)

    def abs(self):
        """abs(vctr1 self) -> double"""
        return _model.vctr1_abs(self)

    def pow(self, *args):
        """
        pow(vctr1 self, int const n) -> vctr1
        pow(vctr1 self, double n) -> vctr1
        """
        return _model.vctr1_pow(self, *args)

    def is_nan(self):
        """is_nan(vctr1 self) -> bool"""
        return _model.vctr1_is_nan(self)

    def is_bad(self):
        """is_bad(vctr1 self) -> bool"""
        return _model.vctr1_is_bad(self)

    def circ(self, *args):
        """circ(vctr1 self, int l) -> vctr1"""
        return _model.vctr1_circ(self, *args)

    def c_str(self, separator=" ", format="%g"):
        """
        c_str(vctr1 self, char const * separator=" ", char const * format="%g") -> char const
        c_str(vctr1 self, char const * separator=" ") -> char const
        c_str(vctr1 self) -> char const *
        """
        return _model.vctr1_c_str(self, separator, format)

    def __rmul__(self, *args):
        """
        __rmul__(vctr1 self, double x) -> vctr1
        __rmul__(vctr1 self, indx1 I) -> vctr1
        __rmul__(vctr1 self, PyObject * t) -> vctr1
        """
        return _model.vctr1___rmul__(self, *args)

    def __len__(self):
        """__len__(vctr1 self) -> int const"""
        return _model.vctr1___len__(self)

    def __getitem__(self, *args):
        """__getitem__(vctr1 self, int i) -> double"""
        return _model.vctr1___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(vctr1 self, int i, double x)"""
        return _model.vctr1___setitem__(self, *args)

    def __getslice__(self, *args):
        """__getslice__(vctr1 self, long a, long b) -> PyObject *"""
        return _model.vctr1___getslice__(self, *args)

    def __setslice__(self, *args):
        """__setslice__(vctr1 self, long a, long b, PyObject * t)"""
        return _model.vctr1___setslice__(self, *args)

    def __str__(self):
        """__str__(vctr1 self) -> PyObject *"""
        return _model.vctr1___str__(self)

    def __repr__(self):
        """__repr__(vctr1 self) -> PyObject *"""
        return _model.vctr1___repr__(self)

    def __getstate__(self):
        """__getstate__(vctr1 self) -> PyObject *"""
        return _model.vctr1___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(vctr1 self, PyObject * t)"""
        return _model.vctr1___C_setstate__(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::vctr<(1,double)> self, double val=0) -> vctr1
        __init__(aiv::vctr<(1,double)> self) -> vctr1
        __init__(aiv::vctr<(1,double)> self, double const * Ap) -> vctr1
        __init__(aiv::vctr<(1,double)> self, vctr1 v) -> vctr1
        __init__(aiv::vctr<(1,double)> self, PyObject * t) -> vctr1
        """
        this = _model.new_vctr1(*args)
        try: self.this.append(this)
        except: self.this = this
    def __hash__(self):
        """__hash__(vctr1 self) -> long"""
        return _model.vctr1___hash__(self)

    def py_debug_info(self, *args):
        """py_debug_info(vctr1 self, aiv::debug_info & S)"""
        return _model.vctr1_py_debug_info(self, *args)

    __swig_destroy__ = _model.delete_vctr1
    __del__ = lambda self : None;
vctr1_swigregister = _model.vctr1_swigregister
vctr1_swigregister(vctr1)

def Vctr( *L ) : v = getattr( import_aivlib( 'vctr%i'%len(L) ), 'vctr%i'%len(L) )(); v[:] = tuple(L); return v
def _vctr1__xor__( a,b ) :  
  try : return Vctr(*map( float.__mul__, tuple(a),tuple(b) ) )  
  except : return  Vctr(*(tuple(a)[:b]+tuple(a)[b+1:]))
vctr1.__xor__ = _vctr1__xor__ 
vctr1.__or__ =lambda a,b : Vctr(*(tuple(a)+tuple(((b,),b)[b.__class__.__name__.startswith('vctr')])))  
vctr1.__ror__=lambda a,b : Vctr(*(tuple(((b,),b)[b.__class__.__name__.startswith('vctr')])+tuple(a)))  
vctr1.__setstate__ = _setstate 

class indx3(_object):
    """Proxy of C++ aiv::indx<(3)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, indx3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, indx3, name)
    def volume(self):
        """volume(indx3 self) -> long"""
        return _model.indx3_volume(self)

    def __lt__(self, *args):
        """
        __lt__(indx3 self, indx3 r) -> bool
        __lt__(indx3 self, PyObject * t) -> bool
        __lt__(indx3 self, long i) -> bool
        """
        return _model.indx3___lt__(self, *args)

    def __le__(self, *args):
        """
        __le__(indx3 self, indx3 r) -> bool
        __le__(indx3 self, PyObject * t) -> bool
        __le__(indx3 self, long i) -> bool
        """
        return _model.indx3___le__(self, *args)

    def __gt__(self, *args):
        """
        __gt__(indx3 self, indx3 r) -> bool
        __gt__(indx3 self, PyObject * t) -> bool
        __gt__(indx3 self, long i) -> bool
        """
        return _model.indx3___gt__(self, *args)

    def __ge__(self, *args):
        """
        __ge__(indx3 self, indx3 r) -> bool
        __ge__(indx3 self, PyObject * t) -> bool
        __ge__(indx3 self, long i) -> bool
        """
        return _model.indx3___ge__(self, *args)

    def __eq__(self, *args):
        """
        __eq__(indx3 self, indx3 r) -> bool
        __eq__(indx3 self, PyObject * t) -> bool
        __eq__(indx3 self, long i) -> bool
        """
        return _model.indx3___eq__(self, *args)

    def __ne__(self, *args):
        """
        __ne__(indx3 self, indx3 r) -> bool
        __ne__(indx3 self, PyObject * t) -> bool
        __ne__(indx3 self, long i) -> bool
        """
        return _model.indx3___ne__(self, *args)

    def __add__(self, *args):
        """
        __add__(indx3 self, indx3 r) -> indx3
        __add__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(indx3 self, indx3 r) -> indx3
        __sub__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___sub__(self, *args)

    def __xor__(self, *args):
        """
        __xor__(indx3 self, indx3 r) -> indx3
        __xor__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___xor__(self, *args)

    def __mul__(self, *args):
        """
        __mul__(indx3 self, indx3 r) -> long
        __mul__(indx3 self, int j) -> indx3
        """
        return _model.indx3___mul__(self, *args)

    def __imul__(self, *args):
        """__imul__(indx3 self, int j) -> indx3"""
        return _model.indx3___imul__(self, *args)

    def __neg__(self):
        """__neg__(indx3 self) -> indx3"""
        return _model.indx3___neg__(self)

    def __ixor__(self, *args):
        """
        __ixor__(indx3 self, indx3 r) -> indx3
        __ixor__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___ixor__(self, *args)

    def __iadd__(self, *args):
        """
        __iadd__(indx3 self, indx3 r) -> indx3
        __iadd__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___iadd__(self, *args)

    def __isub__(self, *args):
        """
        __isub__(indx3 self, indx3 r) -> indx3
        __isub__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___isub__(self, *args)

    def __lshift__(self, *args):
        """
        __lshift__(indx3 self, indx3 b) -> indx3
        __lshift__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___lshift__(self, *args)

    def __rshift__(self, *args):
        """
        __rshift__(indx3 self, indx3 b) -> indx3
        __rshift__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___rshift__(self, *args)

    def __ilshift__(self, *args):
        """
        __ilshift__(indx3 self, indx3 b) -> indx3
        __ilshift__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___ilshift__(self, *args)

    def __irshift__(self, *args):
        """
        __irshift__(indx3 self, indx3 b) -> indx3
        __irshift__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___irshift__(self, *args)

    def __mod__(self, *args):
        """
        __mod__(indx3 self, indx3 b) -> indx3
        __mod__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___mod__(self, *args)

    def __imod__(self, *args):
        """
        __imod__(indx3 self, indx3 b) -> indx3
        __imod__(indx3 self, PyObject * t) -> indx3
        """
        return _model.indx3___imod__(self, *args)

    def __rmod__(self, *args):
        """__rmod__(indx3 self, long x) -> indx3"""
        return _model.indx3___rmod__(self, *args)

    def __div__(self, *args):
        """
        __div__(indx3 self, indx3 b) -> indx3
        __div__(indx3 self, PyObject * t) -> indx3
        __div__(indx3 self, int x) -> indx3
        """
        return _model.indx3___div__(self, *args)

    def __idiv__(self, *args):
        """
        __idiv__(indx3 self, indx3 b) -> indx3
        __idiv__(indx3 self, PyObject * t) -> indx3
        __idiv__(indx3 self, int x) -> indx3
        """
        return _model.indx3___idiv__(self, *args)

    def circ(self, *args):
        """circ(indx3 self, int l) -> indx3"""
        return _model.indx3_circ(self, *args)

    def c_str(self, separator=" ", format="%i"):
        """
        c_str(indx3 self, char const * separator=" ", char const * format="%i") -> char const
        c_str(indx3 self, char const * separator=" ") -> char const
        c_str(indx3 self) -> char const *
        """
        return _model.indx3_c_str(self, separator, format)

    def __contains__(self, *args):
        """__contains__(indx3 self, indx3 I) -> bool"""
        return _model.indx3___contains__(self, *args)

    def __rmul__(self, *args):
        """__rmul__(indx3 self, int x) -> indx3"""
        return _model.indx3___rmul__(self, *args)

    def __len__(self):
        """__len__(indx3 self) -> int const"""
        return _model.indx3___len__(self)

    def __int__(self):
        """__int__(indx3 self) -> long"""
        return _model.indx3___int__(self)

    def __getitem__(self, *args):
        """__getitem__(indx3 self, int i) -> int"""
        return _model.indx3___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(indx3 self, int i, int x)"""
        return _model.indx3___setitem__(self, *args)

    def __getslice__(self, *args):
        """__getslice__(indx3 self, long a, long b) -> PyObject *"""
        return _model.indx3___getslice__(self, *args)

    def __setslice__(self, *args):
        """__setslice__(indx3 self, long a, long b, PyObject * t)"""
        return _model.indx3___setslice__(self, *args)

    def __str__(self):
        """__str__(indx3 self) -> PyObject *"""
        return _model.indx3___str__(self)

    def __repr__(self):
        """__repr__(indx3 self) -> PyObject *"""
        return _model.indx3___repr__(self)

    def __getstate__(self):
        """__getstate__(indx3 self) -> PyObject *"""
        return _model.indx3___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(indx3 self, PyObject * t)"""
        return _model.indx3___C_setstate__(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::indx<(3)> self, int val=0) -> indx3
        __init__(aiv::indx<(3)> self) -> indx3
        __init__(aiv::indx<(3)> self, int const * Ap) -> indx3
        __init__(aiv::indx<(3)> self, PyObject * t) -> indx3
        """
        this = _model.new_indx3(*args)
        try: self.this.append(this)
        except: self.this = this
    def __hash__(self):
        """__hash__(indx3 self) -> long"""
        return _model.indx3___hash__(self)

    def py_debug_info(self, *args):
        """py_debug_info(indx3 self, aiv::debug_info & S)"""
        return _model.indx3_py_debug_info(self, *args)

    def less(self, *args):
        """
        less(indx3 self, indx3 N) -> bool
        less(indx3 self, indx3 N, int const seq) -> bool
        """
        return _model.indx3_less(self, *args)

    def next(self, *args):
        """
        next(indx3 self, indx3 finish) -> bool
        next(indx3 self, indx3 start, indx3 finish) -> bool
        next(indx3 self, indx3 start, indx3 finish, int const seq, int const direct=0) -> bool
        next(indx3 self, indx3 start, indx3 finish, int const seq) -> bool
        next(indx3 self, indx3 finish, int const seq, int const direct=0) -> bool
        next(indx3 self, indx3 finish, int const seq) -> bool
        """
        return _model.indx3_next(self, *args)

    def z_next(self, *args):
        """
        z_next(indx3 self, int const rank) -> bool
        z_next(indx3 self, int const rank, int const seq) -> bool
        """
        return _model.indx3_z_next(self, *args)

    __swig_destroy__ = _model.delete_indx3
    __del__ = lambda self : None;
indx3_swigregister = _model.indx3_swigregister
indx3_swigregister(indx3)

def Indx( *L ) : v = getattr( import_aivlib( 'indx%i'%len(L) ), 'indx%i'%len(L) )(); v[:] = tuple(L); return v
indx3.__rcmp__=lambda a,b : -b.__cmp__(a) 
def _indx3__xor__( a,b ) :  
  try : return Indx(*map( int.__mul__, tuple(a),tuple(b) ) )  
  except : return  Indx(*(tuple(a)[:b]+tuple(a)[b+1:]))
indx3.__xor__ = _indx3__xor__ 
indx3.__or__ =lambda a,b : Indx(*(tuple(a)+tuple(((b,),b)[b.__class__.__name__.startswith('indx')])))  
indx3.__ror__=lambda a,b : Indx(*(tuple(((b,),b)[b.__class__.__name__.startswith('indx')])+tuple(a)))  
indx3.__setstate__ = _setstate 

class vctr3(_object):
    """Proxy of C++ aiv::vctr<(3,double)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vctr3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vctr3, name)
    def __lt__(self, *args):
        """
        __lt__(vctr3 self, vctr3 r) -> bool
        __lt__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___lt__(self, *args)

    def __le__(self, *args):
        """
        __le__(vctr3 self, vctr3 r) -> bool
        __le__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___le__(self, *args)

    def __gt__(self, *args):
        """
        __gt__(vctr3 self, vctr3 r) -> bool
        __gt__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___gt__(self, *args)

    def __ge__(self, *args):
        """
        __ge__(vctr3 self, vctr3 r) -> bool
        __ge__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___ge__(self, *args)

    def __eq__(self, *args):
        """
        __eq__(vctr3 self, vctr3 r) -> bool
        __eq__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___eq__(self, *args)

    def __ne__(self, *args):
        """
        __ne__(vctr3 self, vctr3 r) -> bool
        __ne__(vctr3 self, PyObject * t) -> bool
        """
        return _model.vctr3___ne__(self, *args)

    def __and__(self, *args):
        """
        __and__(vctr3 self, vctr3 r) -> double
        __and__(vctr3 self, PyObject * t) -> double
        """
        return _model.vctr3___and__(self, *args)

    def __add__(self, *args):
        """
        __add__(vctr3 self, vctr3 r) -> vctr3
        __add__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___add__(self, *args)

    def __sub__(self, *args):
        """
        __sub__(vctr3 self, vctr3 r) -> vctr3
        __sub__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___sub__(self, *args)

    def __iadd__(self, *args):
        """
        __iadd__(vctr3 self, vctr3 r) -> vctr3
        __iadd__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___iadd__(self, *args)

    def __isub__(self, *args):
        """
        __isub__(vctr3 self, vctr3 r) -> vctr3
        __isub__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___isub__(self, *args)

    def __lshift__(self, *args):
        """
        __lshift__(vctr3 self, vctr3 r) -> vctr3
        __lshift__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___lshift__(self, *args)

    def __rshift__(self, *args):
        """
        __rshift__(vctr3 self, vctr3 r) -> vctr3
        __rshift__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___rshift__(self, *args)

    def __ilshift__(self, *args):
        """
        __ilshift__(vctr3 self, vctr3 r) -> vctr3
        __ilshift__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___ilshift__(self, *args)

    def __irshift__(self, *args):
        """
        __irshift__(vctr3 self, vctr3 r) -> vctr3
        __irshift__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___irshift__(self, *args)

    def __xor__(self, *args):
        """
        __xor__(vctr3 self, vctr3 r) -> vctr3
        __xor__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___xor__(self, *args)

    def __ixor__(self, *args):
        """
        __ixor__(vctr3 self, vctr3 r) -> vctr3
        __ixor__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___ixor__(self, *args)

    def __mul__(self, *args):
        """
        __mul__(vctr3 self, vctr3 r) -> double
        __mul__(vctr3 self, indx3 I) -> vctr3
        __mul__(vctr3 self, PyObject * t) -> vctr3
        __mul__(vctr3 self, double x) -> vctr3
        """
        return _model.vctr3___mul__(self, *args)

    def __imul__(self, *args):
        """
        __imul__(vctr3 self, indx3 I) -> vctr3
        __imul__(vctr3 self, PyObject * t) -> vctr3
        __imul__(vctr3 self, double x) -> vctr3
        """
        return _model.vctr3___imul__(self, *args)

    def __div__(self, *args):
        """
        __div__(vctr3 self, vctr3 r) -> indx3
        __div__(vctr3 self, indx3 I) -> vctr3
        __div__(vctr3 self, PyObject * t) -> vctr3
        __div__(vctr3 self, double x) -> vctr3
        """
        return _model.vctr3___div__(self, *args)

    def __idiv__(self, *args):
        """
        __idiv__(vctr3 self, indx3 I) -> vctr3
        __idiv__(vctr3 self, PyObject * t) -> vctr3
        __idiv__(vctr3 self, double x) -> vctr3
        """
        return _model.vctr3___idiv__(self, *args)

    def __neg__(self):
        """__neg__(vctr3 self) -> vctr3"""
        return _model.vctr3___neg__(self)

    def abs(self):
        """abs(vctr3 self) -> double"""
        return _model.vctr3_abs(self)

    def pow(self, *args):
        """
        pow(vctr3 self, int const n) -> vctr3
        pow(vctr3 self, double n) -> vctr3
        """
        return _model.vctr3_pow(self, *args)

    def is_nan(self):
        """is_nan(vctr3 self) -> bool"""
        return _model.vctr3_is_nan(self)

    def is_bad(self):
        """is_bad(vctr3 self) -> bool"""
        return _model.vctr3_is_bad(self)

    def circ(self, *args):
        """circ(vctr3 self, int l) -> vctr3"""
        return _model.vctr3_circ(self, *args)

    def c_str(self, separator=" ", format="%g"):
        """
        c_str(vctr3 self, char const * separator=" ", char const * format="%g") -> char const
        c_str(vctr3 self, char const * separator=" ") -> char const
        c_str(vctr3 self) -> char const *
        """
        return _model.vctr3_c_str(self, separator, format)

    def __rmul__(self, *args):
        """
        __rmul__(vctr3 self, double x) -> vctr3
        __rmul__(vctr3 self, indx3 I) -> vctr3
        __rmul__(vctr3 self, PyObject * t) -> vctr3
        """
        return _model.vctr3___rmul__(self, *args)

    def __len__(self):
        """__len__(vctr3 self) -> int const"""
        return _model.vctr3___len__(self)

    def __getitem__(self, *args):
        """__getitem__(vctr3 self, int i) -> double"""
        return _model.vctr3___getitem__(self, *args)

    def __setitem__(self, *args):
        """__setitem__(vctr3 self, int i, double x)"""
        return _model.vctr3___setitem__(self, *args)

    def __getslice__(self, *args):
        """__getslice__(vctr3 self, long a, long b) -> PyObject *"""
        return _model.vctr3___getslice__(self, *args)

    def __setslice__(self, *args):
        """__setslice__(vctr3 self, long a, long b, PyObject * t)"""
        return _model.vctr3___setslice__(self, *args)

    def __str__(self):
        """__str__(vctr3 self) -> PyObject *"""
        return _model.vctr3___str__(self)

    def __repr__(self):
        """__repr__(vctr3 self) -> PyObject *"""
        return _model.vctr3___repr__(self)

    def __getstate__(self):
        """__getstate__(vctr3 self) -> PyObject *"""
        return _model.vctr3___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(vctr3 self, PyObject * t)"""
        return _model.vctr3___C_setstate__(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::vctr<(3,double)> self, double val=0) -> vctr3
        __init__(aiv::vctr<(3,double)> self) -> vctr3
        __init__(aiv::vctr<(3,double)> self, double const * Ap) -> vctr3
        __init__(aiv::vctr<(3,double)> self, vctr3 v) -> vctr3
        __init__(aiv::vctr<(3,double)> self, PyObject * t) -> vctr3
        """
        this = _model.new_vctr3(*args)
        try: self.this.append(this)
        except: self.this = this
    def __hash__(self):
        """__hash__(vctr3 self) -> long"""
        return _model.vctr3___hash__(self)

    def py_debug_info(self, *args):
        """py_debug_info(vctr3 self, aiv::debug_info & S)"""
        return _model.vctr3_py_debug_info(self, *args)

    __swig_destroy__ = _model.delete_vctr3
    __del__ = lambda self : None;
vctr3_swigregister = _model.vctr3_swigregister
vctr3_swigregister(vctr3)

vctr3.__mod__=lambda a,b : vctr3((a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])) 
def Vctr( *L ) : v = getattr( import_aivlib( 'vctr%i'%len(L) ), 'vctr%i'%len(L) )(); v[:] = tuple(L); return v
def _vctr3__xor__( a,b ) :  
  try : return Vctr(*map( float.__mul__, tuple(a),tuple(b) ) )  
  except : return  Vctr(*(tuple(a)[:b]+tuple(a)[b+1:]))
vctr3.__xor__ = _vctr3__xor__ 
vctr3.__or__ =lambda a,b : Vctr(*(tuple(a)+tuple(((b,),b)[b.__class__.__name__.startswith('vctr')])))  
vctr3.__ror__=lambda a,b : Vctr(*(tuple(((b,),b)[b.__class__.__name__.startswith('vctr')])+tuple(a)))  
vctr3.__setstate__ = _setstate 


def angle(*args):
  """
    angle(vctr1 a, vctr1 b, vctr1 c) -> double
    angle(vctr3 a, vctr3 b, vctr3 c) -> double
    """
  return _model.angle(*args)
class arrC3(_object):
    """Proxy of C++ aiv::array<(Cell,3)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, arrC3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, arrC3, name)
    __repr__ = _swig_repr
    dim = _model.arrC3_dim
    dump_dim = _model.arrC3_dump_dim
    __swig_getmethods__["N"] = _model.arrC3_N_get
    if _newclass:N = _swig_property(_model.arrC3_N_get)
    def clean(self):
        """clean(arrC3 self)"""
        return _model.arrC3_clean(self)

    def init(self, *args):
        """init(arrC3 self, indx3 AN)"""
        return _model.arrC3_init(self, *args)

    def mmap(self, *args):
        """
        mmap(arrC3 self, indx3 AN, char const * fname, long offset, bool write=False)
        mmap(arrC3 self, indx3 AN, char const * fname, long offset)
        """
        return _model.arrC3_mmap(self, *args)

    def info(self, *args):
        """
        info(arrC3 self, aiv::Ostream & S=mystdout)
        info(arrC3 self)
        """
        return _model.arrC3_info(self, *args)

    def solid_dims(self):
        """solid_dims(arrC3 self) -> int"""
        return _model.arrC3_solid_dims(self)

    def nb_shift(self, *args):
        """nb_shift(arrC3 self, int pos, int axe) -> long"""
        return _model.arrC3_nb_shift(self, *args)

    def index(self, *args):
        """
        index(arrC3 self, indx3 I) -> long
        index(arrC3 self, long i) -> long
        """
        return _model.arrC3_index(self, *args)

    def get(self, *args):
        """
        get(arrC3 self, long i) -> Cell
        get(arrC3 self, long i) -> Cell
        """
        return _model.arrC3_get(self, *args)

    __swig_destroy__ = _model.delete_arrC3
    __del__ = lambda self : None;
    def copy(self):
        """copy(arrC3 self) -> arrC3"""
        return _model.arrC3_copy(self)

    def crop(self, *args):
        """
        crop(arrC3 self, indx3 a, indx3 b, indx3 step=aiv::indx(1)) -> arrC3
        crop(arrC3 self, indx3 a, indx3 b) -> arrC3
        """
        return _model.arrC3_crop(self, *args)

    def swap(self, *args):
        """swap(arrC3 self, int i, int j) -> arrC3"""
        return _model.arrC3_swap(self, *args)

    def flip(self, *args):
        """flip(arrC3 self, int i) -> arrC3"""
        return _model.arrC3_flip(self, *args)

    def __len__(self):
        """__len__(arrC3 self) -> int"""
        return _model.arrC3___len__(self)

    def __getitem__(self, *args):
        """
        __getitem__(arrC3 self, indx3 I) -> Cell
        __getitem__(arrC3 self, long I) -> Cell
        __getitem__(arrC3 self, PyObject * t) -> Cell
        """
        return _model.arrC3___getitem__(self, *args)

    def __setitem__(self, *args):
        """
        __setitem__(arrC3 self, indx3 I, Cell val)
        __setitem__(arrC3 self, long I, Cell val)
        __setitem__(arrC3 self, PyObject * t, Cell val)
        """
        return _model.arrC3___setitem__(self, *args)

    def __getstate__(self):
        """__getstate__(arrC3 self) -> PyObject *"""
        return _model.arrC3___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(arrC3 self, PyObject * t)"""
        return _model.arrC3___C_setstate__(self, *args)

    def dump(self, *args):
        """
        dump(arrC3 self, aiv::Ostream & S, char const * header=None)
        dump(arrC3 self, aiv::Ostream & S)
        """
        return _model.arrC3_dump(self, *args)

    def update(self, *args):
        """
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell), long shift_in=-1) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell)) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1)) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx()) -> indx3
        update(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx()) -> indx3
        update(arrC3 self, aiv::Istream & S) -> indx3
        update(arrC3 self, arrC3 A) -> indx3
        """
        return _model.arrC3_update(self, *args)

    def load(self, *args):
        """
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell), long shift_in=-1)
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell))
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3)
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None)
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1))
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx())
        load(arrC3 self, aiv::Istream & S, indx3 a=aiv::indx())
        load(arrC3 self, aiv::Istream & S)
        load(arrC3 self, char const * fname, int D2=3, int axe=3-1, int * offset=None, int max=-1, bool write=False)
        load(arrC3 self, char const * fname, int D2=3, int axe=3-1, int * offset=None, int max=-1)
        load(arrC3 self, char const * fname, int D2=3, int axe=3-1, int * offset=None)
        load(arrC3 self, char const * fname, int D2=3, int axe=3-1)
        load(arrC3 self, char const * fname, int D2=3)
        load(arrC3 self, char const * fname)
        """
        return _model.arrC3_load(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::array<(Cell,3)> self) -> arrC3
        __init__(aiv::array<(Cell,3)> self, indx3 AN) -> arrC3
        __init__(aiv::array<(Cell,3)> self, indx3 AN, Cell Ap) -> arrC3
        __init__(aiv::array<(Cell,3)> self, arrC3 A) -> arrC3
        __init__(aiv::array<(Cell,3)> self, indx3 AN, char const * fname, int offset, bool write=False) -> arrC3
        __init__(aiv::array<(Cell,3)> self, indx3 AN, char const * fname, int offset) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell), long shift_in=-1) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell)) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1)) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx()) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S, indx3 a=aiv::indx()) -> arrC3
        __init__(aiv::array<(Cell,3)> self, aiv::Istream & S) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname, int D2=3, int axe=3-1, int * offset=None, int max=-1, bool write=False) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname, int D2=3, int axe=3-1, int * offset=None, int max=-1) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname, int D2=3, int axe=3-1, int * offset=None) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname, int D2=3, int axe=3-1) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname, int D2=3) -> arrC3
        __init__(aiv::array<(Cell,3)> self, char const * fname) -> arrC3
        """
        this = _model.new_arrC3(*args)
        try: self.this.append(this)
        except: self.this = this
    def py_debug_info(self, *args):
        """py_debug_info(arrC3 self, aiv::debug_info & S)"""
        return _model.arrC3_py_debug_info(self, *args)

arrC3_swigregister = _model.arrC3_swigregister
arrC3_swigregister(arrC3)

class meshC3(arrC3):
    """Proxy of C++ aiv::mesh<(Cell,3)> class"""
    __swig_setmethods__ = {}
    for _s in [arrC3]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, meshC3, name, value)
    __swig_getmethods__ = {}
    for _s in [arrC3]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, meshC3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["min"] = _model.meshC3_min_set
    __swig_getmethods__["min"] = _model.meshC3_min_get
    if _newclass:min = _swig_property(_model.meshC3_min_get, _model.meshC3_min_set)
    __swig_setmethods__["max"] = _model.meshC3_max_set
    __swig_getmethods__["max"] = _model.meshC3_max_get
    if _newclass:max = _swig_property(_model.meshC3_max_get, _model.meshC3_max_set)
    __swig_setmethods__["step"] = _model.meshC3_step_set
    __swig_getmethods__["step"] = _model.meshC3_step_get
    if _newclass:step = _swig_property(_model.meshC3_step_get, _model.meshC3_step_set)
    __swig_setmethods__["ext_val"] = _model.meshC3_ext_val_set
    __swig_getmethods__["ext_val"] = _model.meshC3_ext_val_get
    if _newclass:ext_val = _swig_property(_model.meshC3_ext_val_get, _model.meshC3_ext_val_set)
    def info(self, *args):
        """
        info(meshC3 self, aiv::Ostream & S=mystdout)
        info(meshC3 self)
        """
        return _model.meshC3_info(self, *args)

    def copy(self):
        """copy(meshC3 self) -> meshC3"""
        return _model.meshC3_copy(self)

    def crop(self, *args):
        """
        crop(meshC3 self, indx3 a, indx3 b, indx3 istep=aiv::indx(1)) -> meshC3
        crop(meshC3 self, indx3 a, indx3 b) -> meshC3
        crop(meshC3 self, vctr3 a, vctr3 b, indx3 istep=aiv::indx(1)) -> meshC3
        crop(meshC3 self, vctr3 a, vctr3 b) -> meshC3
        """
        return _model.meshC3_crop(self, *args)

    def swap(self, *args):
        """swap(meshC3 self, int i, int j) -> meshC3"""
        return _model.meshC3_swap(self, *args)

    def flip(self, *args):
        """flip(meshC3 self, int i) -> meshC3"""
        return _model.meshC3_flip(self, *args)

    def __getitem__(self, *args):
        """
        __getitem__(meshC3 self, long i) -> Cell
        __getitem__(meshC3 self, indx3 I) -> Cell
        __getitem__(meshC3 self, PyObject * t) -> Cell
        __getitem__(meshC3 self, vctr3 r) -> Cell
        """
        return _model.meshC3___getitem__(self, *args)

    def __setitem__(self, *args):
        """
        __setitem__(meshC3 self, long i, Cell v)
        __setitem__(meshC3 self, indx3 I, Cell v)
        __setitem__(meshC3 self, PyObject * t, Cell val)
        __setitem__(meshC3 self, vctr3 r, Cell v)
        """
        return _model.meshC3___setitem__(self, *args)

    def __contains__(self, *args):
        """__contains__(meshC3 self, vctr3 r) -> bool"""
        return _model.meshC3___contains__(self, *args)

    def __getstate__(self):
        """__getstate__(meshC3 self) -> PyObject *"""
        return _model.meshC3___getstate__(self)

    def __C_setstate__(self, *args):
        """__C_setstate__(meshC3 self, PyObject * t)"""
        return _model.meshC3___C_setstate__(self, *args)

    def dump(self, *args):
        """
        dump(meshC3 self, aiv::Ostream & S, char const * head=None)
        dump(meshC3 self, aiv::Ostream & S)
        """
        return _model.meshC3_dump(self, *args)

    def load(self, *args):
        """
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell), long shift_in=-1)
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3, int szT=sizeof(Cell))
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None, int D2=3)
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1), 
            int * pos=None)
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx(), indx3 step=aiv::indx(1))
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx(), indx3 b=aiv::indx())
        load(meshC3 self, aiv::Istream & S, indx3 a=aiv::indx())
        load(meshC3 self, aiv::Istream & S)
        """
        return _model.meshC3_load(self, *args)

    def __init__(self, *args): 
        """
        __init__(aiv::mesh<(Cell,3)> self) -> meshC3
        __init__(aiv::mesh<(Cell,3)> self, indx3 AN) -> meshC3
        __init__(aiv::mesh<(Cell,3)> self, indx3 AN, vctr3 Amin, vctr3 Amax, Cell Ap) -> meshC3
        __init__(aiv::mesh<(Cell,3)> self, meshC3 M) -> meshC3
        __init__(aiv::mesh<(Cell,3)> self, arrC3 A) -> meshC3
        __init__(aiv::mesh<(Cell,3)> self, aiv::Istream & S) -> meshC3
        """
        this = _model.new_meshC3(*args)
        try: self.this.append(this)
        except: self.this = this
    def py_debug_info(self, *args):
        """py_debug_info(meshC3 self, aiv::debug_info & S)"""
        return _model.meshC3_py_debug_info(self, *args)

    __swig_destroy__ = _model.delete_meshC3
    __del__ = lambda self : None;
meshC3_swigregister = _model.meshC3_swigregister
meshC3_swigregister(meshC3)

class mult_arrC3(_object):
    """Proxy of C++ aiv::multiarray<(aiv::array<(Cell,3)>)> class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mult_arrC3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mult_arrC3, name)
    __repr__ = _swig_repr
    dim = _model.mult_arrC3_dim
    __swig_setmethods__["N"] = _model.mult_arrC3_N_set
    __swig_getmethods__["N"] = _model.mult_arrC3_N_get
    if _newclass:N = _swig_property(_model.mult_arrC3_N_get, _model.mult_arrC3_N_set)
    __swig_setmethods__["ext_val"] = _model.mult_arrC3_ext_val_set
    __swig_getmethods__["ext_val"] = _model.mult_arrC3_ext_val_get
    if _newclass:ext_val = _swig_property(_model.mult_arrC3_ext_val_get, _model.mult_arrC3_ext_val_set)
    def __init__(self): 
        """__init__(aiv::multiarray<(aiv::array<(Cell,3)>)> self) -> mult_arrC3"""
        this = _model.new_mult_arrC3()
        try: self.this.append(this)
        except: self.this = this
    def add_arr(self, *args):
        """add_arr(mult_arrC3 self, indx3 offset, arrC3 arr)"""
        return _model.mult_arrC3_add_arr(self, *args)

    def dump(self, *args):
        """
        dump(mult_arrC3 self, aiv::Ostream & S, char const * header=None)
        dump(mult_arrC3 self, aiv::Ostream & S)
        """
        return _model.mult_arrC3_dump(self, *args)

    def load(self, *args):
        """load(mult_arrC3 self, aiv::Istream & S)"""
        return _model.mult_arrC3_load(self, *args)

    def __len__(self):
        """__len__(mult_arrC3 self) -> int"""
        return _model.mult_arrC3___len__(self)

    def __getitem__(self, *args):
        """
        __getitem__(mult_arrC3 self, indx3 I) -> Cell
        __getitem__(mult_arrC3 self, long I) -> Cell
        """
        return _model.mult_arrC3___getitem__(self, *args)

    def __setitem__(self, *args):
        """
        __setitem__(mult_arrC3 self, indx3 I, Cell val)
        __setitem__(mult_arrC3 self, long I, Cell val)
        """
        return _model.mult_arrC3___setitem__(self, *args)

    __swig_destroy__ = _model.delete_mult_arrC3
    __del__ = lambda self : None;
mult_arrC3_swigregister = _model.mult_arrC3_swigregister
mult_arrC3_swigregister(mult_arrC3)

arrC3.__setstate__, meshC3.__setstate__ = _setstate, _setstate 

def splice1(*args):
  """
    splice1(arrC3 A, indx3 pos) -> aiv::array< Cell,1 >
    splice1(meshC3 A, indx3 pos) -> aiv::mesh< Cell,1 >
    """
  return _model.splice1(*args)

def splice2(*args):
  """
    splice2(arrC3 A, indx3 pos) -> aiv::array< Cell,2 >
    splice2(meshC3 A, indx3 pos) -> aiv::mesh< Cell,2 >
    """
  return _model.splice2(*args)
from aivlib.vctr3 import * 
from aivlib.mystream import * 
from aivlib.mystream import *; 
# This file is compatible with both classic and new-style classes.


